on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main

name: Build/Publish Image Docker
jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 0lucho0/ifp-www:${{ github.sha }}
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/ifp-webapp www=0lucho0/ifp-www:${{ github.sha }}
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/ifp-webapp